/**
 * Word data — Day 2 Section B
 * Loaded by ../game/ engine.
 */
(function(V8) {
  'use strict';
  V8.WORD_PACK = {
    schemaVersion: 1,
    id: 'day2-section-b',
    title: 'Day 2 · Section B',
    words: [
{e:"judge",p:"/dʒʌdʒ/",c:["判断"]},
{e:"hi",p:"/haɪ/",c:["嗨"]},
{e:"clothing",p:"/ˈkloʊðɪŋ/",c:["服装"]},
{e:"foreign",p:"/ˈfɔːrən/",c:["外国的"]},
{e:"generate",p:"/ˈdʒenəreɪt/",c:["产生"]},
{e:"I",p:"/aɪ/",c:["我"]},
{e:"both",p:"/boʊθ/",c:["两者"]},
{e:"slide",p:"/slaɪd/",c:["滑动"]},
{e:"emperor",p:"/ˈempərər/",c:["皇帝"]},
{e:"assess",p:"/əˈses/",c:["评定"]},
{e:"branch",p:"/bræntʃ/",c:["分支"]},
{e:"compulsory",p:"/kəmˈpʌlsəri/",c:["义务的"]},
{e:"steady",p:"/ˈstedi/",c:["稳定的"]},
{e:"additional",p:"/əˈdɪʃənl/",c:["额外的"]},
{e:"merge",p:"/mɜːrdʒ/",c:["合并"]},
{e:"university",p:"/ˌjuːnɪˈvɜːrsəti/",c:["大学"]},
{e:"population",p:"/ˌpɑːpjuˈleɪʃn/",c:["人口"]},
{e:"bribe",p:"/braɪb/",c:["贿赂"]},
{e:"retail",p:"/ˈriːteɪl; rɪˈteɪl/",c:["零售"]},
{e:"list",p:"/lɪst/",c:["列表"]},
{e:"servant",p:"/ˈsɜːrvənt/",c:["仆人"]},
{e:"selfish",p:"/ˈselfɪʃ/",c:["自私的"]},
{e:"niece",p:"/niːs/",c:["侄女"]},
{e:"staff",p:"/stæf/",c:["全体职员"]},
{e:"bypass",p:"/ˈbaɪpæs/",c:["绕过"]},
{e:"concession",p:"/kənˈseʃn/",c:["让步"]},
{e:"intimidate",p:"/ɪnˈtɪmɪdeɪt/",c:["恐吓"]},
{e:"sing",p:"/sɪŋ/",c:["唱歌"]},
{e:"mobilize",p:"/ˈmoʊbəlaɪz/",c:["动员"]},
{e:"pig",p:"/pɪɡ/",c:["猪"]},
{e:"share",p:"/ʃer/",c:["分享"]},
{e:"subjective",p:"/səbˈdʒektɪv/",c:["主观的"]},
{e:"around",p:"/əˈraʊnd/",c:["周围"]},
{e:"naturally",p:"/ˈnætʃrəli/",c:["自然地"]},
{e:"hose",p:"/hoʊz/",c:["软管"]},
{e:"cheese",p:"/tʃiːz/",c:["奶酪"]},
{e:"fossil",p:"/ˈfɑːsl/",c:["化石"]},
{e:"blanket",p:"/ˈblæŋkɪt/",c:["毛毯"]},
{e:"senate",p:"/ˈsenət/",c:["参议院"]},
{e:"compartment",p:"/kəmˈpɑːrtmənt/",c:["隔间"]},
{e:"there",p:"/ðer/",c:["在那里"]},
{e:"snack",p:"/snæk/",c:["小吃"]},
{e:"Soviet",p:"/,sovɪ'et/",c:["苏维埃"]},
{e:"to",p:"/tə,tu,tuː/",c:["向"]},
{e:"project",p:"/ˈprɑːdʒekt/",c:["项目"]},
{e:"rip",p:"/rɪp/",c:["撕"]},
{e:"suburb",p:"/ˈsʌbɜːrb/",c:["郊区"]},
{e:"dialog",p:"/ˈdaɪəlɔːɡ/",c:["对话"]},
{e:"intermittent",p:"/ˌɪntərˈmɪtənt/",c:["间歇的"]},
{e:"descent",p:"/dɪˈsent/",c:["下降"]}
    ],
  };
})(window.V8 = window.V8 || {});
