/**
 * Word data — Day 2 Section A
 * Loaded by ../game/ engine.
 */
(function(V8) {
  'use strict';
  V8.WORD_PACK = {
    schemaVersion: 1,
    id: 'day2-section-a',
    title: 'Day 2 · Section A',
    words: [
{e:"punctual",p:"/ˈpʌŋktʃuəl/",c:["准时的"]},
{e:"conceal",p:"/kənˈsiːl/",c:["隐藏"]},
{e:"salad",p:"/ˈsæləd/",c:["色拉"]},
{e:"match",p:"/mætʃ/",c:["比赛"]},
{e:"necessary",p:"/ˈnesəseri/",c:["必要的"]},
{e:"fasten",p:"/ˈfæsn/",c:["固定"]},
{e:"suck",p:"/sʌk/",c:["吸吮"]},
{e:"although",p:"/ɔːlˈðoʊ/",c:["虽然"]},
{e:"basket",p:"/ˈbæskɪt/",c:["篮子"]},
{e:"government",p:"/ˈɡʌvərnmənt/",c:["政府"]},
{e:"masculine",p:"/ˈmæskjəlɪn/",c:["男性的"]},
{e:"slaughter",p:"/ˈslɔːtər/",c:["屠杀"]},
{e:"lieutenant",p:"/luːˈtenənt/",c:["中尉"]},
{e:"shell",p:"/ʃel/",c:["壳"]},
{e:"sequence",p:"/ˈsiːkwəns/",c:["顺序"]},
{e:"innocent",p:"/ˈɪnəsnt/",c:["无辜的"]},
{e:"dissatisfy",p:"/dɪs'sætɪs,fai/",c:["使不满"]},
{e:"horsepower",p:"/ˈhɔːrspaʊər/",c:["马力"]},
{e:"strip",p:"/strɪp/",c:["剥去"]},
{e:"twice",p:"/twaɪs/",c:["两次"]},
{e:"six",p:"/sɪks/",c:["六"]},
{e:"wound",p:"/wuːnd; waʊnd/",c:["伤口"]},
{e:"however",p:"/haʊˈevər/",c:["然而"]},
{e:"steer",p:"/stɪr/",c:["驾驶"]},
{e:"owe",p:"/oʊ/",c:["欠"]},
{e:"congratulation",p:"/kənˌɡrætʃuˈleɪʃn/",c:["祝贺"]},
{e:"slot",p:"/slɑːt/",c:["位置"]},
{e:"Chinese",p:"/ˌtʃaɪˈniːz/",c:["中文"]},
{e:"gain",p:"/ɡeɪn/",c:["获得"]},
{e:"basin",p:"/ˈbeɪsn/",c:["盆地"]},
{e:"twelfth",p:"/twelfθ/",c:["第十二"]},
{e:"random",p:"/ˈrændəm/",c:["随机的"]},
{e:"gulf",p:"/ɡʌlf/",c:["海湾"]},
{e:"idea",p:"/aɪˈdiːə/",c:["想法"]},
{e:"busy",p:"/ˈbɪzi/",c:["忙碌的"]},
{e:"full",p:"/fʊl/",c:["完全的"]},
{e:"police",p:"/pəˈliːs/",c:["警察"]},
{e:"lucky",p:"/ˈlʌki/",c:["幸运的"]},
{e:"transcend",p:"/trænˈsend/",c:["超越"]},
{e:"historian",p:"/hɪˈstɔːriən/",c:["历史学家"]},
{e:"British",p:"/ˈbrɪtɪʃ/",c:["英国的"]},
{e:"castle",p:"/ˈkæsl/",c:["城堡"]},
{e:"scream",p:"/skriːm/",c:["尖叫"]},
{e:"commitment",p:"/kəˈmɪtmənt/",c:["承诺"]},
{e:"feminine",p:"/ˈfemənɪn/",c:["女性的"]},
{e:"clarify",p:"/ˈklærəfaɪ/",c:["澄清"]},
{e:"brave",p:"/breɪv/",c:["勇敢的"]},
{e:"butterfly",p:"/ˈbʌtərflaɪ/",c:["蝴蝶"]},
{e:"independence",p:"/ˌɪndɪˈpendəns/",c:["独立"]},
{e:"distil",p:"/dɪˈstɪl/",c:["蒸馏"]}
    ],
  };
})(window.V8 = window.V8 || {});
