/**
 * Word data — Day 2 Section C
 * Loaded by ../game/ engine.
 */
(function(V8) {
  'use strict';
  V8.WORD_PACK = {
    schemaVersion: 1,
    id: 'day2-section-c',
    title: 'Day 2 · Section C',
    words: [
{e:"gentle",p:"/ˈdʒentl/",c:["温和的"]},
{e:"pasture",p:"/ˈpæstʃər/",c:["牧场"]},
{e:"careless",p:"/ˈkerləs/",c:["粗心的"]},
{e:"pronounce",p:"/prəˈnaʊns/",c:["发音"]},
{e:"joyful",p:"/ˈdʒɔɪfl/",c:["欢喜的"]},
{e:"length",p:"/leŋkθ/",c:["长度"]},
{e:"degrade",p:"/dɪˈɡreɪd/",c:["贬低"]},
{e:"assign",p:"/əˈsaɪn/",c:["分配"]},
{e:"exile",p:"/ˈeksaɪl,ˈeɡzaɪl/",c:["流放"]},
{e:"radium",p:"/ˈreɪdiəm/",c:["镭"]},
{e:"thermal",p:"/ˈθɜːrml/",c:["热的"]},
{e:"increasingly",p:"/ɪnˈkriːsɪŋli/",c:["越来越多地"]},
{e:"oar",p:"/ɔːr/",c:["桨"]},
{e:"undermine",p:"/ˌʌndərˈmaɪn/",c:["破坏"]},
{e:"weary",p:"/ˈwɪri/",c:["疲倦的"]},
{e:"captain",p:"/ˈkæptɪn/",c:["队长"]},
{e:"alter",p:"/ˈɔːltər/",c:["改变"]},
{e:"stability",p:"/stəˈbɪləti/",c:["稳定性"]},
{e:"address",p:"/əˈdres,ˈædres/",c:["地址"]},
{e:"excursion",p:"/ɪkˈskɜːrʒn/",c:["远足"]},
{e:"island",p:"/ˈaɪlənd/",c:["岛"]},
{e:"vex",p:"/veks/",c:["使烦恼"]},
{e:"indignant",p:"/ɪnˈdɪɡnənt/",c:["愤愤不平的"]},
{e:"congress",p:"/ˈkɑːŋɡrəs/",c:["国会"]},
{e:"amuse",p:"/əˈmjuːz/",c:["娱乐"]},
{e:"unknown",p:"/ˌʌnˈnoʊn/",c:["未知的"]},
{e:"sow",p:"/soʊ; saʊ/",c:["播种"]},
{e:"visualize",p:"/ˈvɪʒuəlaɪz/",c:["想象"]},
{e:"instantaneous",p:"/ˌɪnstənˈteɪniəs/",c:["瞬间的"]},
{e:"stand",p:"/stænd/",c:["站立"]},
{e:"esthetic",p:"/esˈθetɪk/",c:["审美的"]},
{e:"mosquito",p:"/məˈskiːtoʊ/",c:["蚊子"]},
{e:"assert",p:"/əˈsɜːrt/",c:["主张"]},
{e:"worm",p:"/wɜːrm/",c:["虫"]},
{e:"analyse",p:"/ˈænəlaɪz/",c:["分析"]},
{e:"November",p:"/noʊˈvembər/",c:["十一月"]},
{e:"bureau",p:"/ˈbjʊroʊ/",c:["局"]},
{e:"stall",p:"/stɔːl/",c:["货摊"]},
{e:"stir",p:"/stɜːr/",c:["搅拌"]},
{e:"semester",p:"/sɪˈmestər/",c:["学期"]},
{e:"telephone",p:"/ˈtelɪfoʊn/",c:["电话"]},
{e:"limitation",p:"/ˌlɪmɪˈteɪʃn/",c:["限制"]},
{e:"certainly",p:"/ˈsɜːrtnli/",c:["当然"]},
{e:"advertise",p:"/ˈædvərtaɪz/",c:["做广告"]},
{e:"relay",p:"/ˈriːleɪ,rɪˈleɪ/",c:["转播"]},
{e:"funeral",p:"/ˈfjuːnərəl/",c:["葬礼"]},
{e:"buy",p:"/baɪ/",c:["购买"]},
{e:"mark",p:"/mɑːrk/",c:["标志"]},
{e:"recipe",p:"/ˈresəpi/",c:["食谱"]},
{e:"shot",p:"/ʃɑːt/",c:["发射"]}
    ],
  };
})(window.V8 = window.V8 || {});
