/**
 * Word data — Day 1 Section A
 * Loaded by ../game/ engine.
 */
(function(V8) {
  'use strict';
  V8.WORD_PACK = {
    schemaVersion: 1,
    id: 'day1-section-a',
    title: 'Day 1 · Section A',
    words: [
{e:"ornament",p:"/ˈɔːrnəmənt/",c:["装饰"]},
{e:"apprehension",p:"/ˌæprɪˈhenʃn/",c:["理解"]},
{e:"indicative",p:"/ɪnˈdɪkətɪv/",c:["指示的"]},
{e:"hinder",p:"/ˈhɪndər/",c:["阻碍"]},
{e:"municipal",p:"/mjuːˈnɪsɪpl/",c:["市政的"]},
{e:"statue",p:"/ˈstætʃuː/",c:["雕像"]},
{e:"emerge",p:"/ɪˈmɜːrdʒ/",c:["浮现"]},
{e:"spider",p:"/ˈspaɪdər/",c:["蜘蛛"]},
{e:"cloth",p:"/klɔːθ/",c:["布"]},
{e:"drop",p:"/drɑːp/",c:["下降"]},
{e:"accord",p:"/əˈkɔːrd/",c:["一致"]},
{e:"underline",p:"/ˌʌndərˈlaɪn/",c:["强调"]},
{e:"plateau",p:"/plæˈtoʊ/",c:["高原"]},
{e:"commonwealth",p:"/ˈkɑːmənwelθ/",c:["联邦"]},
{e:"vicinity",p:"/vəˈsɪnəti/",c:["邻近"]},
{e:"corporate",p:"/ˈkɔːrpərət/",c:["公司的"]},
{e:"characterize",p:"/ˈkærəktəraɪz/",c:["描绘特性"]},
{e:"healthy",p:"/ˈhelθi/",c:["健康的"]},
{e:"horror",p:"/ˈhɔːrər/",c:["惊骇"]},
{e:"update",p:"/ˌʌpˈdeɪt/",c:["更新"]},
{e:"effort",p:"/ˈefərt/",c:["努力"]},
{e:"dialect",p:"/ˈdaɪəlekt/",c:["方言"]},
{e:"advocate",p:"/ˈædvəkeɪt; ˈædvəkət/",c:["提倡"]},
{e:"father",p:"/ˈfɑːðər/",c:["父亲"]},
{e:"word",p:"/wɜːrd/",c:["单词"]},
{e:"discrete",p:"/dɪˈskriːt/",c:["离散的"]},
{e:"deny",p:"/dɪˈnaɪ/",c:["否认"]},
{e:"digest",p:"/daɪˈdʒest/",c:["消化"]},
{e:"physical",p:"/ˈfɪzɪkl/",c:["身体的"]},
{e:"spectacular",p:"/spekˈtækjələr/",c:["壮观的"]},
{e:"weave",p:"/wiːv/",c:["编织"]},
{e:"eloquent",p:"/ˈeləkwənt/",c:["雄辩的"]},
{e:"eve",p:"/iːv/",c:["前夕"]},
{e:"yoke",p:"/joʊk/",c:["束缚"]},
{e:"settle",p:"/ˈsetl/",c:["解决"]},
{e:"radiant",p:"/ˈreɪdiənt/",c:["光芒四射的"]},
{e:"district",p:"/ˈdɪstrɪkt/",c:["区域"]},
{e:"cradle",p:"/ˈkreɪdl/",c:["摇篮"]},
{e:"temper",p:"/ˈtempər/",c:["脾气"]},
{e:"stab",p:"/stæb/",c:["刺"]},
{e:"work",p:"/wɜːrk/",c:["工作"]},
{e:"empty",p:"/ˈempti/",c:["空的"]},
{e:"mix",p:"/mɪks/",c:["混合"]},
{e:"Oceania",p:"/ˌoʊʃiˈɑːniə/",c:["大洋洲"]},
{e:"clumsy",p:"/ˈklʌmzi/",c:["笨拙的"]},
{e:"her",p:"/hə(r)/",c:["她"]},
{e:"relax",p:"/rɪˈlæks/",c:["放松"]},
{e:"bull",p:"/bʊl/",c:["公牛"]},
{e:"explode",p:"/ɪkˈsploʊd/",c:["爆炸"]},
{e:"bay",p:"/beɪ/",c:["海湾"]}
    ],
  };
})(window.V8 = window.V8 || {});
