/**
 * Word data — Day 1 Section B
 * Loaded by ../game/ engine.
 */
(function(V8) {
  'use strict';
  V8.WORD_PACK = {
    schemaVersion: 1,
    id: 'day1-section-b',
    title: 'Day 1 · Section B',
    words: [
{e:"rid",p:"/rɪd/",c:["使摆脱"]},
{e:"evil",p:"/ˈiːvl,ˈiːvɪl/",c:["邪恶的"]},
{e:"saw",p:"/sɔː/",c:["锯"]},
{e:"winter",p:"/ˈwɪntər/",c:["冬季"]},
{e:"furnish",p:"/ˈfɜːrnɪʃ/",c:["提供"]},
{e:"quiver",p:"/ˈkwɪvər/",c:["颤抖"]},
{e:"imitate",p:"/ˈɪmɪteɪt/",c:["模仿"]},
{e:"intrinsic",p:"/ɪnˈtrɪnzɪk/",c:["本质的"]},
{e:"advertisement",p:"/ˌædvərˈtaɪzmənt/",c:["广告"]},
{e:"married",p:"/ˈmærid/",c:["已婚的"]},
{e:"pupil",p:"/ˈpjuːpl/",c:["学生"]},
{e:"auto",p:"/ˈɔːtoʊ/",c:["汽车"]},
{e:"left",p:"/left/",c:["左边的"]},
{e:"defence",p:"/dɪˈfens/",c:["防御"]},
{e:"theirs",p:"/ðerz/",c:["他们的"]},
{e:"file",p:"/faɪl/",c:["文件"]},
{e:"garage",p:"/ˈɡærɑːʒ/",c:["车库"]},
{e:"treasure",p:"/ˈtreʒər/",c:["财富"]},
{e:"Polish",p:"/ˈpɑːlɪʃ/",c:["波兰的"]},
{e:"compatible",p:"/kəmˈpætəbl/",c:["兼容的"]},
{e:"customer",p:"/ˈkʌstəmər/",c:["顾客"]},
{e:"outcome",p:"/ˈaʊtkʌm/",c:["结果"]},
{e:"hate",p:"/heɪt/",c:["憎恨"]},
{e:"reed",p:"/riːd/",c:["芦苇"]},
{e:"efficient",p:"/ɪˈfɪʃnt/",c:["有效率的"]},
{e:"alien",p:"/ˈeɪliən/",c:["外国的"]},
{e:"aunt",p:"/ænt/",c:["阿姨"]},
{e:"experimental",p:"/ɪkˌsperɪˈmentl/",c:["实验的"]},
{e:"Mediterranean",p:"/ˌmedɪtəˈreɪniən/",c:["地中海"]},
{e:"recently",p:"/ˈriːsntli/",c:["最近"]},
{e:"gently",p:"/ˈdʒentli/",c:["轻轻地"]},
{e:"multiple",p:"/ˈmʌltɪpl/",c:["多重的"]},
{e:"vulgar",p:"/ˈvʌlɡər/",c:["粗俗的"]},
{e:"cite",p:"/saɪt/",c:["引用"]},
{e:"principle",p:"/ˈprɪnsəpl/",c:["原理"]},
{e:"alliance",p:"/əˈlaɪəns/",c:["联盟"]},
{e:"liter",p:"/ˈliːtər/",c:["公升"]},
{e:"spiral",p:"/ˈspaɪrəl/",c:["螺旋形的"]},
{e:"repertoire",p:"/ˈrepərtwɑːr/",c:["全部节目"]},
{e:"wind",p:"/wɪnd; waɪnd/",c:["风"]},
{e:"lofty",p:"/ˈlɔːfti/",c:["高的"]},
{e:"criticize",p:"/ˈkrɪtɪsaɪz/",c:["批评"]},
{e:"heart",p:"/hɑːrt/",c:["心脏"]},
{e:"disposition",p:"/ˌdɪspəˈzɪʃn/",c:["性情"]},
{e:"minor",p:"/ˈmaɪnər/",c:["次要的"]},
{e:"sixty",p:"/ˈsɪksti/",c:["六十"]},
{e:"employee",p:"/ɪmˈplɔɪiː/",c:["雇员"]},
{e:"woman",p:"/ˈwʊmən/",c:["妇女"]},
{e:"eclipse",p:"/ɪˈklɪps/",c:["日蚀"]},
{e:"scrape",p:"/skreɪp/",c:["刮"]}
    ],
  };
})(window.V8 = window.V8 || {});
