/**
 * Word data — Day 1 Section C
 * Loaded by ../game/ engine.
 */
(function(V8) {
  'use strict';
  V8.WORD_PACK = {
    schemaVersion: 1,
    id: 'day1-section-c',
    title: 'Day 1 · Section C',
    words: [
{e:"happiness",p:"/ˈhæpinəs/",c:["幸福"]},
{e:"consequently",p:"/ˈkɑːnsɪkwentli/",c:["因此"]},
{e:"bounce",p:"/baʊns/",c:["弹跳"]},
{e:"wheel",p:"/wiːl/",c:["车轮"]},
{e:"mankind",p:"/mænˈkaɪnd/",c:["人类"]},
{e:"colonial",p:"/kəˈloʊniəl/",c:["殖民的"]},
{e:"encounter",p:"/ɪnˈkaʊntər/",c:["遇到"]},
{e:"boom",p:"/buːm/",c:["繁荣"]},
{e:"standpoint",p:"/ˈstændpɔɪnt/",c:["立场"]},
{e:"assault",p:"/əˈsɔːlt/",c:["攻击"]},
{e:"jury",p:"/ˈdʒʊri/",c:["陪审团"]},
{e:"win",p:"/wɪn/",c:["赢得"]},
{e:"calendar",p:"/ˈkælɪndər/",c:["日历"]},
{e:"specialize",p:"/ˈspeʃəlaɪz/",c:["专门从事"]},
{e:"unjust",p:"/ˌʌnˈdʒʌst/",c:["不公平的"]},
{e:"visit",p:"/ˈvɪzɪt/",c:["访问"]},
{e:"lunar",p:"/ˈluːnər/",c:["月球的"]},
{e:"usually",p:"/ˈjuːʒəli/",c:["通常"]},
{e:"marry",p:"/ˈmæri/",c:["结婚"]},
{e:"seller",p:"/ˈselər/",c:["卖方"]},
{e:"trumpet",p:"/ˈtrʌmpɪt/",c:["喇叭"]},
{e:"preposition",p:"/ˌprepəˈzɪʃn/",c:["介词"]},
{e:"foam",p:"/foʊm/",c:["泡沫"]},
{e:"sixteen",p:"/ˌsɪksˈtiːn/",c:["十六"]},
{e:"sexual",p:"/ˈsekʃuəl/",c:["性的"]},
{e:"zealous",p:"/ˈzeləs/",c:["热心的"]},
{e:"foreigner",p:"/ˈfɔːrənər/",c:["外国人"]},
{e:"technique",p:"/tekˈniːk/",c:["技巧"]},
{e:"offence",p:"/əˈfens/",c:["过错"]},
{e:"deal",p:"/diːl/",c:["处理"]},
{e:"jeopardize",p:"/ˈdʒepərdaɪz/",c:["危害"]},
{e:"bid",p:"/bɪd/",c:["出价"]},
{e:"breakfast",p:"/ˈbrekfəst/",c:["早餐"]},
{e:"enrich",p:"/ɪnˈrɪtʃ/",c:["使富足"]},
{e:"pure",p:"/pjʊr/",c:["纯的"]},
{e:"choice",p:"/tʃɔɪs/",c:["选择"]},
{e:"exquisite",p:"/ɪkˈskwɪzɪt/",c:["精致的"]},
{e:"sale",p:"/seɪl/",c:["销售"]},
{e:"purely",p:"/ˈpjʊrli/",c:["纯粹地"]},
{e:"adhere",p:"/ədˈhɪr/",c:["坚持"]},
{e:"presumably",p:"/prɪˈzuːməbli/",c:["大概"]},
{e:"hundred",p:"/ˈhʌndrəd/",c:["一百"]},
{e:"slightly",p:"/ˈslaɪtli/",c:["轻微地"]},
{e:"repetition",p:"/ˌrepəˈtɪʃn/",c:["重复"]},
{e:"tourist",p:"/ˈtʊrɪst/",c:["游客"]},
{e:"teacher",p:"/ˈtiːtʃər/",c:["教师"]},
{e:"impart",p:"/ɪmˈpɑːrt/",c:["传授"]},
{e:"connection",p:"/kəˈnekʃn/",c:["连接"]},
{e:"prayer",p:"/prer/",c:["祈祷"]},
{e:"usual",p:"/ˈjuːʒuəl,ˈjuːʒəl/",c:["通常的"]}
    ],
  };
})(window.V8 = window.V8 || {});
