/**
 * Word data — Day 3 Section B
 * Loaded by ../game/ engine.
 */
(function(V8) {
  'use strict';
  V8.WORD_PACK = {
    schemaVersion: 1,
    id: 'day3-section-b',
    title: 'Day 3 · Section B',
    words: [
{e:"plague",p:"/pleɪɡ/",c:["瘟疫"]},
{e:"business",p:"/ˈbɪznəs/",c:["商业"]},
{e:"slap",p:"/slæp/",c:["拍击"]},
{e:"rejoice",p:"/rɪˈdʒɔɪs/",c:["高兴"]},
{e:"faith",p:"/feɪθ/",c:["信仰"]},
{e:"God",p:"/ɡɑːd/",c:["神"]},
{e:"residence",p:"/ˈrezɪdəns/",c:["住宅"]},
{e:"publicity",p:"/pʌbˈlɪsəti/",c:["宣传"]},
{e:"pint",p:"/paɪnt/",c:["品脱"]},
{e:"breed",p:"/briːd/",c:["繁殖"]},
{e:"yourself",p:"/jɔːˈself/",c:["你自己"]},
{e:"aluminium",p:"/ˌæljəˈmɪniəm/",c:["铝"]},
{e:"clever",p:"/ˈklevər/",c:["聪明的"]},
{e:"glare",p:"/ɡler/",c:["怒视"]},
{e:"special",p:"/ˈspeʃl/",c:["特别的"]},
{e:"agriculture",p:"/ˈæɡrɪkʌltʃər/",c:["农业"]},
{e:"speak",p:"/spiːk/",c:["说话"]},
{e:"sight",p:"/saɪt/",c:["视力"]},
{e:"exactly",p:"/ɪɡˈzæktli/",c:["精确地"]},
{e:"hole",p:"/hoʊl/",c:["洞"]},
{e:"lick",p:"/lɪk/",c:["舔"]},
{e:"integrity",p:"/ɪnˈteɡrəti/",c:["正直"]},
{e:"regulation",p:"/ˌreɡjuˈleɪʃn/",c:["规则"]},
{e:"wander",p:"/ˈwɑːndər/",c:["漫步"]},
{e:"lantern",p:"/ˈlæntərn/",c:["灯笼"]},
{e:"harsh",p:"/hɑːrʃ/",c:["严厉的"]},
{e:"aloud",p:"/əˈlaʊd/",c:["大声地"]},
{e:"scarf",p:"/skɑːrf/",c:["围巾"]},
{e:"right",p:"/raɪt/",c:["正确的"]},
{e:"meantime",p:"/ˈmiːntaɪm/",c:["同时"]},
{e:"northern",p:"/ˈnɔːrðərn/",c:["北部的"]},
{e:"abundance",p:"/əˈbʌndəns/",c:["充裕"]},
{e:"overall",p:"/ˌoʊvərˈɔːl; ˈoʊvərɔːl/",c:["全部的"]},
{e:"fade",p:"/feɪd/",c:["逐渐消失"]},
{e:"torture",p:"/ˈtɔːrtʃər/",c:["折磨"]},
{e:"coincidence",p:"/koʊˈɪnsɪdəns/",c:["巧合"]},
{e:"skilled",p:"/skɪld/",c:["熟练的"]},
{e:"mutual",p:"/ˈmjuːtʃuəl/",c:["共同的"]},
{e:"ripple",p:"/ˈrɪpl/",c:["波纹"]},
{e:"successor",p:"/səkˈsesər/",c:["继承者"]},
{e:"treason",p:"/ˈtriːzn/",c:["叛国罪"]},
{e:"decline",p:"/dɪˈklaɪn/",c:["下降"]},
{e:"city",p:"/ˈsɪti/",c:["城市"]},
{e:"vibrate",p:"/ˈvaɪbreɪt/",c:["振动"]},
{e:"provoke",p:"/prəˈvoʊk/",c:["激怒"]},
{e:"whisky",p:"/ˈwɪski/",c:["威士忌酒"]},
{e:"pile",p:"/paɪl/",c:["堆"]},
{e:"ballet",p:"/bæˈleɪ/",c:["芭蕾舞"]},
{e:"birth",p:"/bɜːrθ/",c:["出生"]},
{e:"variable",p:"/ˈveriəbl,ˈværiəbl/",c:["可变的"]}
    ],
  };
})(window.V8 = window.V8 || {});
