/**
 * Word data — Day 3 Section A
 * Loaded by ../game/ engine.
 */
(function(V8) {
  'use strict';
  V8.WORD_PACK = {
    schemaVersion: 1,
    id: 'day3-section-a',
    title: 'Day 3 · Section A',
    words: [
{e:"shoulder",p:"/ˈʃoʊldər/",c:["肩膀"]},
{e:"tired",p:"/ˈtaɪərd/",c:["疲倦的"]},
{e:"vicious",p:"/ˈvɪʃəs/",c:["恶毒的"]},
{e:"pink",p:"/pɪŋk/",c:["粉红色"]},
{e:"anger",p:"/ˈæŋɡər/",c:["愤怒"]},
{e:"whistle",p:"/ˈwɪsl/",c:["吹口哨"]},
{e:"meadow",p:"/ˈmedoʊ/",c:["草地"]},
{e:"necklace",p:"/ˈnekləs/",c:["项链"]},
{e:"ant",p:"/ænt/",c:["蚂蚁"]},
{e:"transfer",p:"/trænsˈfɜːr/",c:["转移"]},
{e:"preserve",p:"/prɪˈzɜːrv/",c:["保存"]},
{e:"compress",p:"/kəmˈpres/",c:["压缩"]},
{e:"superior",p:"/suːˈpɪriər/",c:["优秀的"]},
{e:"besides",p:"/bɪˈsaɪdz/",c:["除…之外"]},
{e:"incidentally",p:"/ˌɪnsɪˈdentli/",c:["顺便"]},
{e:"weather",p:"/ˈweðər/",c:["天气"]},
{e:"hypothesis",p:"/haɪˈpɑːθəsɪs/",c:["假设"]},
{e:"coarse",p:"/kɔːrs/",c:["粗糙的"]},
{e:"destroy",p:"/dɪˈstrɔɪ/",c:["破坏"]},
{e:"range",p:"/reɪndʒ/",c:["范围"]},
{e:"politician",p:"/ˌpɑːləˈtɪʃn/",c:["政客"]},
{e:"gallon",p:"/ˈɡælən/",c:["加仑"]},
{e:"afflict",p:"/əˈflɪkt/",c:["折磨"]},
{e:"swim",p:"/swɪm/",c:["游泳"]},
{e:"perfume",p:"/pərˈfjuːm/",c:["香水"]},
{e:"indispensable",p:"/ˌɪndɪˈspensəbl/",c:["不可缺少的"]},
{e:"paradise",p:"/ˈpærədaɪs/",c:["天堂"]},
{e:"generally",p:"/ˈdʒenrəli/",c:["通常"]},
{e:"spiritual",p:"/ˈspɪrɪtʃuəl/",c:["精神的"]},
{e:"valley",p:"/ˈvæli/",c:["山谷"]},
{e:"medium",p:"/ˈmiːdiəm/",c:["中间的"]},
{e:"snow",p:"/snoʊ/",c:["雪"]},
{e:"pie",p:"/paɪ/",c:["馅饼"]},
{e:"offer",p:"/ˈɔːfər/",c:["提供"]},
{e:"temperature",p:"/ˈtemprətʃər,ˈtemprətʃʊr/",c:["温度"]},
{e:"monthly",p:"/ˈmʌnθli/",c:["每月的"]},
{e:"whereby",p:"/werˈbaɪ/",c:["凭借"]},
{e:"terrify",p:"/ˈterɪfaɪ/",c:["恐吓"]},
{e:"gaze",p:"/ɡeɪz/",c:["凝视"]},
{e:"reliability",p:"/rɪˌlaɪəˈbɪləti/",c:["可靠性"]},
{e:"board",p:"/bɔːrd/",c:["木板"]},
{e:"imagine",p:"/ɪˈmædʒɪn/",c:["想象"]},
{e:"direct",p:"/dəˈrekt,daɪˈrekt/",c:["直接的"]},
{e:"republic",p:"/rɪˈpʌblɪk/",c:["共和国"]},
{e:"resonance",p:"/ˈrezənəns/",c:["共振"]},
{e:"preparation",p:"/ˌprepəˈreɪʃn/",c:["准备"]},
{e:"probably",p:"/ˈprɑːbəbli/",c:["很可能"]},
{e:"equilibrium",p:"/ˌiːkwɪˈlɪbriəm/",c:["均衡"]},
{e:"steward",p:"/ˈstuːərd/",c:["乘务员"]},
{e:"gasoline",p:"/ˈɡæsəliːn/",c:["汽油"]}
    ],
  };
})(window.V8 = window.V8 || {});
