/**
 * Word data — Day 3 Section C
 * Loaded by ../game/ engine.
 */
(function(V8) {
  'use strict';
  V8.WORD_PACK = {
    schemaVersion: 1,
    id: 'day3-section-c',
    title: 'Day 3 · Section C',
    words: [
{e:"national",p:"/ˈnæʃnəl/",c:["国家的"]},
{e:"descendant",p:"/dɪˈsendənt/",c:["后裔"]},
{e:"facet",p:"/ˈfæsɪt/",c:["方面"]},
{e:"discrepancy",p:"/dɪˈskrepənsi/",c:["不符"]},
{e:"impossible",p:"/ɪmˈpɑːsəbl/",c:["不可能的"]},
{e:"threat",p:"/θret/",c:["威胁"]},
{e:"Saturday",p:"/'sætədei/",c:["星期六"]},
{e:"ensue",p:"/ɪnˈsuː/",c:["接着发生"]},
{e:"impress",p:"/ɪmˈpres/",c:["给予深刻印象"]},
{e:"attitude",p:"/ˈætɪtuːd/",c:["态度"]},
{e:"rear",p:"/rɪr/",c:["后面"]},
{e:"fundamental",p:"/ˌfʌndəˈmentl/",c:["基本的"]},
{e:"ambassador",p:"/æmˈbæsədər/",c:["大使"]},
{e:"determine",p:"/dɪˈtɜːrmɪn/",c:["决定"]},
{e:"rubber",p:"/ˈrʌbər/",c:["橡胶"]},
{e:"emotion",p:"/ɪˈmoʊʃn/",c:["情感"]},
{e:"regularly",p:"/ˈreɡjələrli/",c:["定期地"]},
{e:"Angle",p:"/ˈæŋɡl/",c:["盎格鲁人"]},
{e:"damn",p:"/dæm/",c:["谴责"]},
{e:"roof",p:"/ruːf/",c:["屋顶"]},
{e:"resistant",p:"/rɪˈzɪstənt/",c:["抵抗的"]},
{e:"ignore",p:"/ɪɡˈnɔːr/",c:["忽视"]},
{e:"spouse",p:"/spaʊs,spaʊz/",c:["配偶"]},
{e:"inevitable",p:"/ɪnˈevɪtəbl/",c:["不可避免的"]},
{e:"beard",p:"/bɪrd/",c:["胡须"]},
{e:"target",p:"/ˈtɑːrɡɪt/",c:["目标"]},
{e:"murmur",p:"/ˈmɜːrmər/",c:["低语"]},
{e:"warehouse",p:"/ˈwerhaʊs/",c:["仓库"]},
{e:"dead",p:"/ded/",c:["无生命的"]},
{e:"gene",p:"/dʒiːn/",c:["基因"]},
{e:"duck",p:"/dʌk/",c:["鸭子"]},
{e:"code",p:"/koʊd/",c:["代码"]},
{e:"when",p:"/wen/",c:["在...的时候"]},
{e:"clasp",p:"/klæsp/",c:["扣子"]},
{e:"couch",p:"/kaʊtʃ/",c:["长沙发"]},
{e:"rise",p:"/raɪz/",c:["上升"]},
{e:"dwell",p:"/dwel/",c:["居住"]},
{e:"pole",p:"/poʊl/",c:["杆"]},
{e:"succeed",p:"/səkˈsiːd/",c:["成功"]},
{e:"necessity",p:"/nəˈsesəti/",c:["需要"]},
{e:"very",p:"/ˈveri/",c:["很"]},
{e:"chart",p:"/tʃɑːrt/",c:["图表"]},
{e:"quarter",p:"/ˈkwɔːrtər/",c:["四分之一"]},
{e:"pierce",p:"/pɪrs/",c:["刺穿"]},
{e:"disclose",p:"/dɪsˈkloʊz/",c:["公开"]},
{e:"salesman",p:"/ˈseɪlzmən/",c:["推销员"]},
{e:"exercise",p:"/ˈeksərsaɪz/",c:["运动"]},
{e:"it",p:"/ɪt/",c:["它"]},
{e:"satisfy",p:"/ˈsætɪsfaɪ/",c:["满足"]},
{e:"migrate",p:"/ˈmaɪɡreɪt/",c:["移居"]}
    ],
  };
})(window.V8 = window.V8 || {});
